apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro1
spec:
  selector:
      matchLabels:
        app: micro1
  replicas: 2
  template:
    metadata:
      labels:
        app: micro1
    spec:
      containers:
        - name: micro1
          image: ashurana31/micro1:micro1
          ports:
            - containerPort: 8080
